//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Watchlist struct {
	ID       int32 `sql:"primary_key"`
	MovieID  *int32
	UserID   int32
	Status   WatchStatus
	Favorite bool
	Comments string
	Rating   *int32
}
