//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var WatchStatus = &struct {
	Unwatched   postgres.StringExpression
	Watching    postgres.StringExpression
	PlanToWatch postgres.StringExpression
	Watched     postgres.StringExpression
}{
	Unwatched:   postgres.NewEnumValue("unwatched"),
	Watching:    postgres.NewEnumValue("watching"),
	PlanToWatch: postgres.NewEnumValue("plan to watch"),
	Watched:     postgres.NewEnumValue("watched"),
}
